In [ ]:
# // 600 500 300 200 50
# // 0.5 0.6 1   1.5 6

# // 600/500 = 1.2 -> * 0.5 = 0.6
# // ...
# // + sum crts up to level priced in egld
# // + sum shards up to level priced in egld
# // + sum tokens up to level priced in egld
# // + rarity in egld about perks 

# prendi tutti gli nft in vendita 
# al prezzo scala tutti gli elementi di valore normalizzando il prezzo in egld 
# per i characters lascia il prezzo di 0 tokens livello 1 rarita' nativa
# per le weapons lasclia il prezzo star uno livello 1

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
data_folder = '../public/data'
dfs = {}
for folder in os.listdir(data_folder):
    if os.path.isdir(os.path.join(data_folder, folder)):
        dfs[folder] = pd.read_json(os.path.join(data_folder, folder, 'nfts.json'), orient='index')

In [26]:
tmp = pd.concat([dfs['CEA-2d29f9'], dfs['GSPACEAPE-08bc2b']]).value_counts('rarityClass').reset_index()
tmp['percent'] = round(tmp['count'] / tmp['count'].sum() *100, 2)
tmp

  rarityClass  count  percent
0      Bronze   5683    34.99
1      Silver   4871    29.99
2        Gold   2848    17.53
3        Epic   2034    12.52
4   Legendary    808     4.97

In [3]:
tmp = dfs["CRHEROES-9edff2"].value_counts('rarityClass').reset_index()
tmp['percent'] = round(tmp['count'] / tmp['count'].sum() *100, 2)
tmp

  rarityClass  count  percent
0        Gold    350    58.33
1        Epic    190    31.67
2   Legendary     60    10.00

In [11]:
tmp = pd.concat([dfs['CRMYTH-546419'], dfs['CRWEAPONS-e5ab49']]).value_counts(['name', 'starLevel']).reset_index()
tmp['percent'] = round(tmp['count'] / tmp['count'].sum() *100, 2)
tmp

                 name  starLevel  count  percent
0        Dragonbreath        1.0    263     6.91
1         Boomstick-X        2.0    223     5.86
2        Mortar Gun X        2.0    219     5.76
3           Railgun-X        2.0    199     5.23
4           Blaster-X        2.0    195     5.12
5         Tesla Gun X        2.0    183     4.81
6           Railgun-X        3.0    152     3.99
7        Mortar Gun X        3.0    152     3.99
8        Mortar Gun X        1.0    152     3.99
9         Boomstick-X        3.0    150     3.94
10          Railgun-X        1.0    145     3.81
11        Tesla Gun X        3.0    145     3.81
12          Blaster-X        3.0    140     3.68
13  Hellfire Launcher        2.0    135     3.55
14        Tesla Gun X        1.0    129     3.39
15         Skybreaker        2.0    127     3.34
16        Boomstick-X        1.0    114     3.00
17          Blaster-X        1.0    100     2.63
18       Dragonbreath        2.0     74     1.94
19        Tesla Gun X        4.0     72     1.89
20        Boomstick-X        4.0     67     1.76
21          Blaster-X        4.0     61     1.60
22          Railgun-X        4.0     59     1.55
23       Mortar Gun X        4.0     57     1.50
24        Boomstick-X        6.0     40     1.05
25  Hellfire Launcher        3.0     39     1.02
26          Blaster-X        5.0     39     1.02
27        Tesla Gun X        6.0     38     1.00
28       Dragonbreath        3.0     36     0.95
29          Blaster-X        6.0     35     0.92
30       Mortar Gun X        6.0     34     0.89
31         Skybreaker        3.0     34     0.89
32        Tesla Gun X        5.0     32     0.84
33        Boomstick-X        5.0     28     0.74
34          Railgun-X        6.0     27     0.71
35       Mortar Gun X        5.0     26     0.68
36          Railgun-X        5.0     16     0.42
37       Dragonbreath        4.0     15     0.39
38       Dragonbreath        5.0     14     0.37
39         Skybreaker        1.0     10     0.26
40  Hellfire Launcher        4.0      9     0.24
41         Skybreaker        4.0      8     0.21
42       Dragonbreath        6.0      5     0.13
43         Skybreaker        5.0      2     0.05
44  Hellfire Launcher        5.0      2     0.05
45         Skybreaker        6.0      1     0.03
46  Hellfire Launcher        6.0      1     0.03
47     Titan Shredder        2.0      1     0.03

In [ ]:
# heatmap perk1 perk2 for each rarity class (for genesis and for heroes)
# heatmap starLevel level for each weapons (crweapons and crmyth)
# heatmap level rarity for each characters (for genesis and for heroes)

In [ ]:
# for each name, plot heatmap of starLevel vs level (there are 6 starLevels and 20 levels)
# display all the possible combinations of starLevel and level
# and count the number of occurrences of each combination

import matplotlib.pyplot as plt
import seaborn as sns

tmp = df[df['starLevel'].notna() & df['level'].notna()]
tmp['starLevel'] = tmp['starLevel'].astype(int)
tmp['level'] = tmp['level'].astype(int)
for name in df['name'].unique():
    tmp2 = tmp[tmp['name'] == name]
    d = tmp2.groupby(['starLevel', 'level']).size().to_dict()
    for i in range(6):
        for j in range(20):
            starLevel = i + 1
            level = j + 1
            if (starLevel, level) not in d:
                d[(starLevel, level)] = 0
    sns.heatmap(pd.Series(d).unstack(fill_value=0), annot=True, fmt='d')
    plt.title(name)
    plt.show()